project:
  type: book

book:
  title: "FCP Practice"
  author: "Anand"
  date: "9/23/2024"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - ps1.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  # pdf:
  #   documentclass: scrreprt



